#!/usr/bin/env bash
# Hostinger / Docker bootstrap for WhisperSTT_API.
# Writes config.local.env from container environment on every start (auto-setup).
set -euo pipefail

MARKER=/var/www/html/.whisperstt-bootstrapped
REPO_ARCHIVE_URL="${NEUS_WHISPER_ARCHIVE_URL:-https://github.com/ZakRowton/APIs/archive/refs/heads/main.tar.gz}"
RAW_BASE="${NEUS_WHISPER_RAW_BASE:-https://raw.githubusercontent.com/ZakRowton/APIs/main/WhisperSTT_API}"

export APACHE_DOCUMENT_ROOT=/var/www/html/public

write_config_local_env() {
  # Always refresh from process env so compose/Hostinger env panel wins.
  cat > /var/www/html/config.local.env <<EOF
# Auto-generated by hostinger-bootstrap.sh — do not edit by hand in Docker.
WHISPER_SERVER_HOST=${WHISPER_SERVER_HOST:-whisper}
WHISPER_SERVER_PORT=${WHISPER_SERVER_PORT:-8081}
WHISPER_SERVER_INFERENCE_PATH=${WHISPER_SERVER_INFERENCE_PATH:-/inference}
WHISPER_MODEL=${WHISPER_MODEL:-models/ggml-base.en.bin}
WHISPER_THREADS=${WHISPER_THREADS:-4}
FFMPEG=${FFMPEG:-ffmpeg}
NEUS_WHISPER_AUTO_START=${NEUS_WHISPER_AUTO_START:-0}
NEUS_WHISPER_MAX_UPLOAD_BYTES=${NEUS_WHISPER_MAX_UPLOAD_BYTES:-26214400}
NEUS_WHISPER_RETRY_ATTEMPTS=${NEUS_WHISPER_RETRY_ATTEMPTS:-3}
NEUS_WHISPER_RETRY_DELAY_MS=${NEUS_WHISPER_RETRY_DELAY_MS:-500}
NEUS_WHISPER_API_KEY=${NEUS_WHISPER_API_KEY:-}
EOF
  chown www-data:www-data /var/www/html/config.local.env 2>/dev/null || true
  echo "Wrote /var/www/html/config.local.env from container environment."
}

if [ ! -f "$MARKER" ]; then
  echo "Bootstrapping WhisperSTT_API from GitHub..."
  apt-get update
  apt-get install -y --no-install-recommends libcurl4-openssl-dev curl ca-certificates tar
  docker-php-ext-install curl
  a2enmod rewrite headers
  rm -rf /var/lib/apt/lists/*

  tmp="$(mktemp -d)"
  curl -fsSL "$REPO_ARCHIVE_URL" -o "$tmp/apis.tgz"
  tar -xzf "$tmp/apis.tgz" -C "$tmp"
  src="$(echo "$tmp"/APIs-*/WhisperSTT_API)"

  mkdir -p /var/www/html
  rm -rf /var/www/html/api /var/www/html/lib /var/www/html/public
  cp -a "$src/api" "$src/lib" "$src/public" /var/www/html/
  cp -a "$src/test.php" "$src/config.example.env" /var/www/html/
  mkdir -p /var/www/html/runtime/uploads /var/www/html/models

  curl -fsSL "$RAW_BASE/docker/apache-neuswhisper.conf" \
    -o /etc/apache2/sites-available/000-default.conf
  curl -fsSL "$RAW_BASE/docker/php-neuswhisper.ini" \
    -o /usr/local/etc/php/conf.d/99-whisperstt.ini

  # Ensure Apache passes Docker env into PHP (belt + suspenders with config.local.env).
  cat > /etc/apache2/conf-available/whisperstt-env.conf <<'APACHE'
PassEnv WHISPER_SERVER_HOST
PassEnv WHISPER_SERVER_PORT
PassEnv WHISPER_SERVER_INFERENCE_PATH
PassEnv WHISPER_MODEL
PassEnv WHISPER_THREADS
PassEnv FFMPEG
PassEnv NEUS_WHISPER_AUTO_START
PassEnv NEUS_WHISPER_MAX_UPLOAD_BYTES
PassEnv NEUS_WHISPER_RETRY_ATTEMPTS
PassEnv NEUS_WHISPER_RETRY_DELAY_MS
PassEnv NEUS_WHISPER_API_KEY
APACHE
  a2enconf whisperstt-env >/dev/null

  chown -R www-data:www-data /var/www/html
  rm -rf "$tmp"
  touch "$MARKER"
  echo "Bootstrap complete."
fi

write_config_local_env

WHISPER_HOST="${WHISPER_SERVER_HOST:-whisper}"
WHISPER_PORT="${WHISPER_SERVER_PORT:-8081}"
DEADLINE=$((SECONDS + 180))
while (( SECONDS < DEADLINE )); do
  if curl -sf "http://${WHISPER_HOST}:${WHISPER_PORT}/" >/dev/null 2>&1; then
    echo "whisper-server reachable at ${WHISPER_HOST}:${WHISPER_PORT}"
    break
  fi
  sleep 2
done

exec apache2-foreground
